version: 2

models:

  - name: bronze_orders
    columns:
      - name: order_id
        tests:
          - not_null
          - unique

  - name: bronze_customers
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique

  - name: silver_orders
    columns:
      - name: order_id
        tests:
          - not_null
          - unique
      - name: customer_id
        tests:
          - not_null
      - name: amount
        tests:
          - not_null
      - name: _status
        tests:
          - not_null
          - accepted_values:
              values: ['completed', 'shipped', 'cancelled']

  - name: silver_customers
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique
      - name: email
        tests:
          - not_null

  - name: dim_customers_gold
    columns:
      - name: customer_key
        tests:
          - not_null
          - unique
      - name: customer_id
        tests:
          - not_null

  - name: fact_sales_gold
    columns:
      - name: order_key
        tests:
          - not_null
          - unique
      - name: customer_key
        tests:
          - not_null
      - name: amount
        tests:
          - not_null